#! /bin/sh
rm -r /sys/fs/cryptofs && rm -r /usr/src/sbin/mount_cryptofs && rm -r /sys/modules/cryptofs \
&& cp -r cryptofs /sys/fs/ \
&& cp -r mount_cryptofs /usr/src/sbin/ \
&& cp -r crypto2/cryptofs /sys/modules/ \
&& cp Making/Makefile /usr/src/sbin/ \
&& make -C /usr/src/sbin/ && make install -C /usr/src/sbin/ \
&& rm /sys/sys/jail.h && cp jail/jail.h /sys/sys/ \
&& rm /sys/sys/vnode.h && cp vnode/vnode.h /sys/sys/ \
&& rm /usr/src/sys/modules/Makefile && cp makeFileForModules/Makefile /usr/src/sys/modules/ \
